// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as Home from "@/app/[locale]/page.info";

export const Locale = makeRoute(
  "/[locale]",
  {
    ...defaultInfo,
    ...Home.Route
  }
);